### ISSUE TITLE
[Project] CLI 4.0.0

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/ionic-cli#3302]
CLI 4 will be released while Framework is in beta.

### 4.0 Checklist

- [x] ~Framework in "healthy" beta~
- [x] Beta docs website
- [x] webview plugin 2.0 (see https://github.com/ionic-team/ionic-cli/issues/3279)
- [x] Test all the things, including migration from CLI 3 apps (`ionic-angular` and `ionic1`)
- [x] Ensure changelog files are ready 
- [x] `ionic link` can take name from `ionic start` (`--name` ?)
- [x] Print message about Ctrl-C for `ionic serve`

### To-do after 4.0 release

- [ ] Check with @nphyatt and @kevinports re: new getting started workflow
- [x] ~Re-enable canary releases~
- [x] ~Document feature flag dev workflow~
