### ISSUE TITLE
CLI 5.0.0

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/ionic-cli#3915]
**This issue is locked, but please feel free to create new issues with any feedback. Thanks!**

---

Project issue for CLI 5, aimed for April-June 2019.

### Breaking Changes (including, but not limited to):

- Drop support for Node 6 & 7
    - Node 6 reaches end-of-life in April 2019: https://github.com/nodejs/Release#release-schedule
    - Require Node 8.9.4 at a minimum (latest Node LTS always recommended)
- Local Resource Generation: https://github.com/ionic-team/ionic-cli/issues/3762
    - Use `cordova-res` by default.
    - Will not support `.ai` or `.psd` files. Only properly sized `.png` files.
    - Allow remote resource generation (the old way), but require a flag for usage.
- `native-run` by default with `ionic cordova run`
    - Switch default address to `localhost` and forward ports by default.
    - Allow app deploy via Cordova (the old way), but require a flag for usage.

### Coming in 5.0.0

- Support for **Ionic React** projects 🚀 (see https://github.com/ionic-team/ionic-cli/pull/3936)
    - `npm i -g ionic@beta`
    - `ionic start --type=react`
- New Colors!
- [native-run](https://github.com/ionic-team/native-run) and [cordova-res](https://github.com/ionic-team/cordova-res) used by default (see above)
- autocompletion for commands when using zsh (see https://github.com/ionic-team/ionic-cli/issues/2482 for bash)

### To-Do

- [x] Switch TypeScript target to [ES2017](https://node.green/#ES2017) or [ES2018](https://node.green/#ES2018), checking caveats 
- [x] Upgrade any dependencies requiring Node 8
- [x] Make `cordova-res` the default
- [x] Make `native-run` the default

**Comment by dwieeb** [comment]
https://github.com/ionic-team/ionic-cli/blob/develop/packages/ionic/CHANGELOG.md#500-2019-05-29
